### ISSUE TITLE
Class file has wrong version 58.0, should be 52.0

### ISSUE THREAD

**Issue by Lucide** [DmitriiShamrikov/mslinks#25]
Hi!,
I'm having troubles getting the built jar from maven central with Gradle. I'm working with Java 1.8 (class version 52.0). I couldn't find any mention of it being Java 14+ only, so I'm making an issue.

I'm using the following Gradle code:
```groovy
dependencies{
    // ...
    implementation("com.github.vatbub:mslinks:1.0.6")
    // ...
}
```

It's the same shown on the project's maven central page.
I'm getting the following error:
```
[...]\manager\control\Controller.java:13: error: cannot access ShellLink
import mslinks.ShellLink;
              ^
  bad class file: [...]\.gradle\caches\modules-2\files-2.1\com.github.vatbub\mslinks\1.0.6\926d37969cba023bb65a93f3bf038585aeab6312\mslinks-1.0.6.jar(mslinks/ShellLink.class)
    class file has wrong version 58.0, should be 52.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.
```

**Comment by tresf** [comment]
The maven repo appears to be managed by @vatbub, not @DmitriiShamrikov.  Pinging, since @vatbub's repo doesn't seem to have an issue tracker.

**Comment by vatbub** [comment]
Hmmm, apparently I compiled that with the wrong JDK 🙈

**Comment by vatbub** [comment]
Actually, I just looked into my commit history and I did that intentionally because of issue #21 and PR #22 . If you need Java 1.8 compatibility, you need version 1.0.5. The only difference is the module info and the resulting incompatibility with Java 1.8.

**Comment by Lucide** [comment]
Damn, that was quite a leap! But in the name of progress...
Thank you, I'll go for 1.0.5
